// <auto-generated />
using System;
using MachineAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MachineAPI.Migrations
{
    [DbContext(typeof(MachineDbContext))]
    [Migration("20260129102023_UseForeignKeysInMachineCorrection")]
    partial class UseForeignKeysInMachineCorrection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MachineAPI.Models.FarmerInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FarmerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("RfId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SmsEnabled")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SocietyId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId")
                        .HasDatabaseName("idx_farmer_id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("RfId")
                        .HasDatabaseName("idx_rf_id");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_status");

                    b.ToTable("farmers", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<int?>("BmcId")
                        .HasColumnType("int")
                        .HasColumnName("BmcId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("InstallationDate");

                    b.Property<bool>("IsMasterMachine")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsMasterMachine");

                    b.Property<DateTime?>("LastSyncDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LastSyncDate");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("MachineId");

                    b.Property<string>("MachineModel")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MachineModel");

                    b.Property<string>("MachineName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MachineName");

                    b.Property<string>("MachineType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("MachineType");

                    b.Property<int>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("SocietyId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IsMasterMachine")
                        .HasDatabaseName("idx_is_master");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("MachineType")
                        .HasDatabaseName("idx_machine_type");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_status");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MachineCorrection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Channel1Clr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_clr");

                    b.Property<decimal?>("Channel1Fat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_fat");

                    b.Property<decimal?>("Channel1Protein")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_protein");

                    b.Property<decimal?>("Channel1Snf")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_snf");

                    b.Property<decimal?>("Channel1Temp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_temp");

                    b.Property<decimal?>("Channel1Water")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_water");

                    b.Property<decimal?>("Channel2Clr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_clr");

                    b.Property<decimal?>("Channel2Fat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_fat");

                    b.Property<decimal?>("Channel2Protein")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_protein");

                    b.Property<decimal?>("Channel2Snf")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_snf");

                    b.Property<decimal?>("Channel2Temp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_temp");

                    b.Property<decimal?>("Channel2Water")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_water");

                    b.Property<decimal?>("Channel3Clr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_clr");

                    b.Property<decimal?>("Channel3Fat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_fat");

                    b.Property<decimal?>("Channel3Protein")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_protein");

                    b.Property<decimal?>("Channel3Snf")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_snf");

                    b.Property<decimal?>("Channel3Temp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_temp");

                    b.Property<decimal?>("Channel3Water")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_water");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_type");

                    b.Property<int>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.HasIndex("MachineId", "SocietyId")
                        .IsUnique()
                        .HasDatabaseName("idx_machine_society");

                    b.ToTable("machine_corrections_from_machine", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MachineCorrectionWeb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Channel1Clr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_clr");

                    b.Property<decimal?>("Channel1Fat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_fat");

                    b.Property<decimal?>("Channel1Protein")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_protein");

                    b.Property<decimal?>("Channel1Snf")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_snf");

                    b.Property<decimal?>("Channel1Temp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_temp");

                    b.Property<decimal?>("Channel1Water")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel1_water");

                    b.Property<decimal?>("Channel2Clr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_clr");

                    b.Property<decimal?>("Channel2Fat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_fat");

                    b.Property<decimal?>("Channel2Protein")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_protein");

                    b.Property<decimal?>("Channel2Snf")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_snf");

                    b.Property<decimal?>("Channel2Temp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_temp");

                    b.Property<decimal?>("Channel2Water")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel2_water");

                    b.Property<decimal?>("Channel3Clr")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_clr");

                    b.Property<decimal?>("Channel3Fat")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_fat");

                    b.Property<decimal?>("Channel3Protein")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_protein");

                    b.Property<decimal?>("Channel3Snf")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_snf");

                    b.Property<decimal?>("Channel3Temp")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_temp");

                    b.Property<decimal?>("Channel3Water")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("channel3_water");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_type");

                    b.Property<int>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_status");

                    b.HasIndex("MachineId", "Status")
                        .HasDatabaseName("idx_machine_status");

                    b.ToTable("machine_corrections", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MachinePasswordLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("change_reason");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("changed_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_successful");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("NewPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("new_password");

                    b.Property<string>("OldPassword")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("old_password");

                    b.Property<string>("PasswordType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("password_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_created_at");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("PasswordType")
                        .HasDatabaseName("idx_password_type");

                    b.ToTable("machine_password_logs", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MachineStatistics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    b.Property<string>("AutoChannel")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AutoChannel");

                    b.Property<int>("CleaningSkip")
                        .HasColumnType("int")
                        .HasColumnName("CleaningSkip");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("DailyCleaning")
                        .HasColumnType("int")
                        .HasColumnName("DailyCleaning");

                    b.Property<int>("Gain")
                        .HasColumnType("int")
                        .HasColumnName("Gain");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("MachineId");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("RecordedAt");

                    b.Property<int>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("SocietyId");

                    b.Property<string>("StatisticsDate")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("StatisticsDate");

                    b.Property<string>("StatisticsTime")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("StatisticsTime");

                    b.Property<int>("TotalTest")
                        .HasColumnType("int")
                        .HasColumnName("TotalTest");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("WeeklyCleaning")
                        .HasColumnType("int")
                        .HasColumnName("WeeklyCleaning");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_created_at");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("RecordedAt")
                        .HasDatabaseName("idx_recorded_at");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.HasIndex("StatisticsDate")
                        .HasDatabaseName("idx_statistics_date");

                    b.HasIndex("MachineId", "StatisticsDate")
                        .HasDatabaseName("idx_machine_date");

                    b.ToTable("machine_statistics", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MachineUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvailableVersion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrentVersion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastChecked")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MachineId")
                        .HasColumnType("int");

                    b.Property<string>("MachineType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SocietyId")
                        .HasColumnType("int");

                    b.Property<string>("UpdateStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UpdateType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_created_at");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("UpdateType")
                        .HasDatabaseName("idx_update_type");

                    b.ToTable("machine_updates", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MilkCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal>("Bonus")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("bonus");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<decimal>("ClrValue")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("clr_value");

                    b.Property<DateOnly>("CollectionDate")
                        .HasColumnType("date")
                        .HasColumnName("collection_date");

                    b.Property<TimeOnly>("CollectionTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("collection_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FarmerId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("farmer_id");

                    b.Property<string>("FarmerName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("farmer_name");

                    b.Property<decimal>("FatPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("fat_percentage");

                    b.Property<decimal>("LactosePercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("lactose_percentage");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_type");

                    b.Property<string>("MachineVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("machine_version");

                    b.Property<decimal>("ProteinPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("protein_percentage");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RatePerLiter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rate_per_liter");

                    b.Property<decimal>("SaltPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("salt_percentage");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("shift_type");

                    b.Property<decimal>("SnfPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("snf_percentage");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("temperature");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WaterPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("water_percentage");

                    b.HasKey("Id");

                    b.HasIndex("CollectionDate")
                        .HasDatabaseName("idx_collection_date");

                    b.HasIndex("FarmerId")
                        .HasDatabaseName("idx_farmer_id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("ShiftType")
                        .HasDatabaseName("idx_shift_type");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.HasIndex("SocietyId", "CollectionDate")
                        .HasDatabaseName("idx_society_date");

                    b.ToTable("milk_collections", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MilkDispatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<decimal>("ClrValue")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("clr_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DispatchDate")
                        .HasColumnType("date")
                        .HasColumnName("dispatch_date");

                    b.Property<string>("DispatchId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("dispatch_id");

                    b.Property<TimeOnly>("DispatchTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("dispatch_time");

                    b.Property<decimal>("FatPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("fat_percentage");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_type");

                    b.Property<string>("MachineVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("machine_version");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RatePerLiter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rate_per_liter");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("shift_type");

                    b.Property<decimal>("SnfPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("snf_percentage");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DispatchDate")
                        .HasDatabaseName("idx_dispatch_date");

                    b.HasIndex("DispatchId")
                        .HasDatabaseName("idx_dispatch_id");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("ShiftType")
                        .HasDatabaseName("idx_shift_type");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.ToTable("milk_dispatches", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MilkSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<string>("Count")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("count");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("customer_name");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("customer_phone");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("MachineType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("machine_type");

                    b.Property<string>("MachineVersion")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("machine_version");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RatePerLiter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rate_per_liter");

                    b.Property<DateOnly>("SalesDate")
                        .HasColumnType("date")
                        .HasColumnName("sales_date");

                    b.Property<TimeOnly>("SalesTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("sales_time");

                    b.Property<string>("ShiftType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("shift_type");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Count")
                        .HasDatabaseName("idx_count");

                    b.HasIndex("MachineId")
                        .HasDatabaseName("idx_machine_id");

                    b.HasIndex("SalesDate")
                        .HasDatabaseName("idx_sales_date");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.ToTable("milk_sales", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.RateChart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("BmcId")
                        .HasColumnType("int")
                        .HasColumnName("bmc_id");

                    b.Property<decimal>("BonusPerLiter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("bonus_per_liter");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<decimal>("FatMax")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("fat_max");

                    b.Property<decimal>("FatMin")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("fat_min");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<decimal>("RatePerLiter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("rate_per_liter");

                    b.Property<decimal>("SnfMax")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("snf_max");

                    b.Property<decimal>("SnfMin")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("snf_min");

                    b.Property<int?>("SocietyId")
                        .HasColumnType("int")
                        .HasColumnName("society_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("BmcId")
                        .HasDatabaseName("idx_bmc_id");

                    b.HasIndex("Channel")
                        .HasDatabaseName("idx_channel");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_is_active");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.HasIndex("ValidFrom")
                        .HasDatabaseName("idx_valid_from");

                    b.HasIndex("ValidTo")
                        .HasDatabaseName("idx_valid_to");

                    b.ToTable("rate_charts", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.Society", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<int?>("BmcId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("SocietyId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BmcId")
                        .HasDatabaseName("idx_bmc_id");

                    b.HasIndex("SocietyId")
                        .HasDatabaseName("idx_society_id");

                    b.ToTable("societies", (string)null);
                });

            modelBuilder.Entity("MachineAPI.Models.MachinePasswordLog", b =>
                {
                    b.HasOne("MachineAPI.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MachineAPI.Models.MachineStatistics", b =>
                {
                    b.HasOne("MachineAPI.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MachineAPI.Models.Society", "Society")
                        .WithMany()
                        .HasForeignKey("SocietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Society");
                });

            modelBuilder.Entity("MachineAPI.Models.MilkCollection", b =>
                {
                    b.HasOne("MachineAPI.Models.Machine", "Machine")
                        .WithMany("MilkCollections")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MachineAPI.Models.MilkDispatch", b =>
                {
                    b.HasOne("MachineAPI.Models.Machine", "Machine")
                        .WithMany("MilkDispatches")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MachineAPI.Models.MilkSale", b =>
                {
                    b.HasOne("MachineAPI.Models.Machine", "Machine")
                        .WithMany("MilkSales")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("MachineAPI.Models.Machine", b =>
                {
                    b.Navigation("MilkCollections");

                    b.Navigation("MilkDispatches");

                    b.Navigation("MilkSales");
                });
#pragma warning restore 612, 618
        }
    }
}
